# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  glad_config = debug
  ImGui_config = debug
  Moxxi_config = debug
  Boids_config = debug
  ShallowWaters_config = debug
  ALG_config = debug
  ALG_Reference_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  glad_config = release
  ImGui_config = release
  Moxxi_config = release
  Boids_config = release
  ShallowWaters_config = release
  ALG_config = release
  ALG_Reference_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  glad_config = dist
  ImGui_config = dist
  Moxxi_config = dist
  Boids_config = dist
  ShallowWaters_config = dist
  ALG_config = dist
  ALG_Reference_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW glad ImGui Moxxi Boids ShallowWaters ALG ALG\ Reference

.PHONY: all clean help $(PROJECTS) Applications Dependencies Plugins References

all: $(PROJECTS)

Applications: Boids ShallowWaters

Dependencies: GLFW ImGui glad

Plugins: ALG

References: ALG Reference

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Moxxi/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C Moxxi/vendor/GLAD -f Makefile config=$(glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Moxxi/vendor/imgui -f Makefile config=$(ImGui_config)
endif

Moxxi: ImGui GLFW glad
ifneq (,$(Moxxi_config))
	@echo "==== Building Moxxi ($(Moxxi_config)) ===="
	@${MAKE} --no-print-directory -C Moxxi -f Makefile config=$(Moxxi_config)
endif

Boids: Moxxi
ifneq (,$(Boids_config))
	@echo "==== Building Boids ($(Boids_config)) ===="
	@${MAKE} --no-print-directory -C Applications/Boids -f Makefile config=$(Boids_config)
endif

ShallowWaters: ALG Moxxi
ifneq (,$(ShallowWaters_config))
	@echo "==== Building ShallowWaters ($(ShallowWaters_config)) ===="
	@${MAKE} --no-print-directory -C Applications/ShallowWaters -f Makefile config=$(ShallowWaters_config)
endif

ALG:
ifneq (,$(ALG_config))
	@echo "==== Building ALG ($(ALG_config)) ===="
	@${MAKE} --no-print-directory -C Plugins/ALG -f Makefile config=$(ALG_config)
endif

ALG\ Reference:
ifneq (,$(ALG_Reference_config))
	@echo "==== Building ALG Reference ($(ALG_Reference_config)) ===="
	@${MAKE} --no-print-directory -C References/ALG-Reference -f Makefile config=$(ALG_Reference_config)
endif

clean:
	@${MAKE} --no-print-directory -C Moxxi/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Moxxi/vendor/GLAD -f Makefile clean
	@${MAKE} --no-print-directory -C Moxxi/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Moxxi -f Makefile clean
	@${MAKE} --no-print-directory -C Applications/Boids -f Makefile clean
	@${MAKE} --no-print-directory -C Applications/ShallowWaters -f Makefile clean
	@${MAKE} --no-print-directory -C Plugins/ALG -f Makefile clean
	@${MAKE} --no-print-directory -C References/ALG-Reference -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   glad"
	@echo "   ImGui"
	@echo "   Moxxi"
	@echo "   Boids"
	@echo "   ShallowWaters"
	@echo "   ALG"
	@echo "   ALG Reference"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"